name: Task T20 CI

on:
  push:
    paths:
      - "ebpf/**"
      - "k8s/**"
      - ".github/workflows/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Kubernetes manifests
        run: kubectl kustomize k8s/ || echo "Simulated manifest linting"

      - name: Check eBPF code presence
        run: |
          if ! ls ebpf/*.{c,py} >/dev/null 2>&1; then
            echo "❌ No eBPF program found"
            exit 1
          fi
