name: Compliance Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REPORT_DIR: reports
  IMAGE_NAME: compliance-demo:ci-build

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install semgrep==1.37.0
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sudo sh -s -- -b /usr/local/bin
          mkdir -p $REPORT_DIR

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Run Semgrep
        run: |
          chmod +x ci-scripts/run_semgrep.sh
          ./ci-scripts/run_semgrep.sh $REPORT_DIR/semgrep.json

      - name: Run Trivy (dependency scan)
        run: |
          chmod +x ci-scripts/run_trivy_deps.sh
          ./ci-scripts/run_trivy_deps.sh $REPORT_DIR/trivy_deps.json

      - name: Run Trivy (image scan)
        run: |
          chmod +x ci-scripts/run_trivy_image.sh
          ./ci-scripts/run_trivy_image.sh $REPORT_DIR/trivy_image.json $IMAGE_NAME

      - name: Run Docker Bench Security
        run: |
          chmod +x ci-scripts/run_docker_bench.sh
          ./ci-scripts/run_docker_bench.sh $REPORT_DIR/docker_bench_raw.txt $REPORT_DIR/docker_bench.json

      - name: Aggregate Reports
        run: |
          python ci-scripts/aggregate_reports.py \
            --semgrep $REPORT_DIR/semgrep.json \
            --trivy-deps $REPORT_DIR/trivy_deps.json \
            --trivy-image $REPORT_DIR/trivy_image.json \
            --docker-bench $REPORT_DIR/docker_bench.json \
            --thresholds thresholds.json \
            --out-dir $REPORT_DIR

      - name: Upload Compliance Reports
        uses: actions/upload-artifact@v4
        with:
          name: compliance-reports
          path: ${{ env.REPORT_DIR }}

      - name: Fail if policy violated
        run: |
          chmod +x ci-scripts/fail_if_thresholds_exceeded.sh
          ./ci-scripts/fail_if_thresholds_exceeded.sh $REPORT_DIR/compliance_report.json thresholds.json

