name: Task T24 CI

on:
  push:
    paths:
      - "logs/**"
      - "scripts/**"

jobs:
  analyze-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run analyzer
        run: |
          python scripts/analyze_logs.py logs/ > report.json || exit 1
          jq . report.json
