apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-compromise
  namespace: demo
  labels:
    name: pod-compromise
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["list","get","patch","update","delete"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create"]
    image: "ubuntu:20.04"
    imagePullPolicy: Always
    args:
    - -c
    - |
      apt-get update && apt-get install -y curl
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl && mv kubectl /usr/local/bin/
      echo "Starting pod compromise simulation"
      TARGET_POD=$(kubectl get pods -l app=nginx -n demo -o jsonpath='{.items[0].metadata.name}')
      echo "Compromising pod: $TARGET_POD"
      kubectl annotate pods $TARGET_POD security.compromised=true -n demo --overwrite
      kubectl label pods $TARGET_POD security-status=compromised -n demo --overwrite
      sleep ${TOTAL_CHAOS_DURATION:-30}
      echo "Pod compromise simulation completed"
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '30'
    labels:
      name: pod-compromise

