name: T15 – AI PR Security Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  security-events: write
  actions: read
  checks: read

jobs:
  snyk-code-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Setup Node.js (needed for Snyk CLI)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # 4. Authenticate Snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 5. Run Snyk scan (JSON + SARIF)
      - name: Install Python dependencies
        run: pip install -r app/requirements.txt
      - name: Run Snyk Code scan
        run: |
          mkdir -p reports
          rm -f reports/snyk-code.json reports/snyk-code.sarif
          snyk code test --json --file=app/app.py --file=app/utils.py > reports/snyk-code.json || true
          snyk code test --sarif --all-projects 2> /dev/null > reports/snyk-code.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}

      # 6. Enforce severity gate (fail on High)
      - name: Enforce severity gate
        run: python scripts/enforce_severity_gate.py reports/snyk-code.json --fail-on high

      # 7. Upload SARIF to GitHub for inline annotations
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/snyk-code.sarif

      # 8. Summarize metrics
      - name: Summarize metrics
        run: python scripts/summarize_metrics.py reports/snyk-code.json reports/summary.json reports/trend.csv .snyk

      # 9. Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-reports
          path: reports/

      # 10. Optional: Handle /snyk-fp comments
      - name: Handle "/snyk-fp" comments
        if: contains(github.event.pull_request.body, '/snyk-fp') || contains(steps.pr-comments.outputs.COMMENTS, '/snyk-fp')
        run: |
          echo "Parsing /snyk-fp commands…"
          python scripts/annotate_false_positive.py --comment "${{ github.event.pull_request.body }}"
          git config user.email "bot@users.noreply.github.com"
          git config user.name "automation-bot"
          git add .snyk && git commit -m "chore(security): add temporary FP ignore via /snyk-fp" || echo "No FP changes"
          git push || true

