name: Threat Modeling as Code CI

on:
  push:
    paths:
      - 'T14-Threat-Modeling-Code/**'
  pull_request:
    paths:
      - 'T14-Threat-Modeling-Code/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Task
        run: |
          echo "Running task: Threat Modeling as Code"
          # Add tool installation or script execution here
