name: K8s Runtime Threat Detection CI

on:
  push:
    paths:
      - 'T02-K8s-Runtime-Threat-Detection/**'
  pull_request:
    paths:
      - 'T02-K8s-Runtime-Threat-Detection/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Task
        run: |
          echo "Running task: K8s Runtime Threat Detection"
          # Add tool installation or script execution here
