apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-role"
        vault.hashicorp.com/agent-inject-secret-db-creds.txt: "database/creds/app-role"
        vault.hashicorp.com/agent-inject-template-db-creds.txt: |
          {{- with secret "database/creds/app-role" -}}
          username = {{ .Data.username }}
          password = {{ .Data.password }}
          {{- end }}
      labels:
        app: myapp
    spec:
      serviceAccountName: app-sa
      containers:
      - name: app
        image: alpine
        command: ["sh", "-c"]
        args: ["cat /vault/secrets/db-creds.txt && sleep 3600"]
