name: Enforce IaC Policies CI

on:
  push:
    paths:
      - 'T01-Enforce-IaC-Policies/**'
  pull_request:
    paths:
      - 'T01-Enforce-IaC-Policies/**'

jobs:
  iac-policy-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AyushTx/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: |
          echo "Initializing Terraform..."
          terraform init

      - name: Terraform Validate
        run: |
          echo "Validating Terraform syntax..."
          terraform validate

      - name: Terraform Plan
        run: |
          echo "Creating Terraform plan..."
          terraform plan -out=plan.tfplan
          terraform show -json plan.tfplan > plan.json

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.52.0/conftest_0.52.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.52.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Security Policy Tests and Save Report
        run: |
          echo "Running IaC security policy validation..."
          conftest test plan.json --policy ../policies/ | tee policy-report.txt

      - name: Upload Policy Report
        uses: actions/upload-artifact@v3
        with:
          name: policy-report
          path: AyushTx/terraform/policy-report.txt
