name: Rubric Evaluation

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: rubric-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  add-ai-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Request Copilot reviewer
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo:  context.repo.repo,
                pull_number: context.issue.number,
                reviewers: ["github-copilot[bot]"]
              });
            } catch (e) {
              core.info("Copilot reviewer not added (maybe already present): " + e.message);
            }

  rubric-evaluation:
    runs-on: ubuntu-latest
    needs: add-ai-reviewer
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Export SHAs for diff
        run: |
          echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Find changed task folders
        id: detect
        run: |
          CHANGED=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" \
            | grep -oE '^T[0-9]{2}[^/]+' \
            | sort -u \
            | jq -R -s -c 'split("\n")[:-1]')
          echo "folders=$CHANGED" >> $GITHUB_OUTPUT
          echo "Changed task folders: $CHANGED"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install --quiet "openai==1.14.3" "httpx<0.27.0" pygithub

      - name: Run rubric evaluator
        if: ${{ steps.detect.outputs.folders != '[]' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          python .github/scripts/rubric_evaluator.py \
            --folders '${{ steps.detect.outputs.folders }}' \
            --pr '${{ github.event.pull_request.number }}'
